source "https://rubygems.org"

gem 'activerecord', '~> 5', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'colorize'

gem "tty-prompt", "~> 0.19.0"

gem "httparty", "~> 0.17.1"
